version: 2
jobs:
  build:
    docker:
      - image: digitalasset/daml-sdk:0.11.19-circleci-master

    steps:
      - checkout

      - run:
          name: DAML Test
          command: da run damlc test Test.daml
